export const CARPET_STATUSES = "CARPET_STATUSES";
export const CARPET_STATUSES_SUCCESS = "CARPET_STATUSES_SUCCESS";
export const CARPET_STATUSES_FAILURE = "CARPET_STATUSES_FAILURE";

export const CARPET_STATUSES_SAGA = "CARPET_STATUSES_SAGA";

export const CARPET_TYPES_FETCHING = "CARPET_TYPES_FETCHING";
export const CARPET_TYPES_SUCCESS = "CARPET_TYPES_SUCCESS";
export const CARPET_TYPES_FAILURE = "CARPET_TYPES_FAILURE";

export const CARPET_TYPES = "CARPET_TYPES";